import * as yaml from 'js-yaml';
import { UserStorySchema } from '../support/schema';
import type { UserStory } from '../support/schema';
import { runSetupSteps, runAssertionSteps } from '../support/steps';

function loadAndRun(yamlContent: string) {
  const docs = yaml.loadAll(yamlContent) as UserStory[];
  for (const doc of docs) {
    if (!doc || !doc.id) continue;
    const story = UserStorySchema.parse(doc);
    const describeFn = story.skip ? describe.skip : story.only ? describe.only : describe;
    describeFn(`${story.id}: ${story.title}`, () => {
      for (const ac of story.acceptance_criteria) {
        const itFn = ac.skip ? it.skip : ac.only ? it.only : it;
        itFn(`${ac.id}: ${ac.title}`, () => {
          if (ac.given) runSetupSteps(ac.given);
          if (ac.when) runSetupSteps(ac.when);
          if (ac.then) runAssertionSteps(ac.then);
        });
      }
    });
  }
}

// US-101: Visitor understands what RootSpec is from the hero
const stories_101 = `
id: US-101
title: Visitor understands what RootSpec is from the hero
acceptance_criteria:
  - id: AC-101-1
    title: Hero headline and subheadline are visible above the fold
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=hero-headline]'
      - shouldExist:
          selector: '[data-test=hero-subheadline]'
    when: []
  - id: AC-101-2
    title: Version badge displays current version
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=version-badge]'
    when: []
`;
loadAndRun(stories_101);

// US-102: Visitor sees meta-banner explaining site was generated by RootSpec pipeline
const stories_102 = `
id: US-102
title: Visitor sees meta-banner explaining site was generated by RootSpec pipeline
acceptance_criteria:
  - id: AC-102-1
    title: Meta banner is visible on page load
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=meta-banner]'
    when: []
  - id: AC-102-2
    title: Meta banner contains links to spec and seed files
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=meta-banner] a[data-test=view-spec-link]'
      - shouldExist:
          selector: '[data-test=meta-banner] a[data-test=view-seed-link]'
    when: []
`;
loadAndRun(stories_102);

// US-103: Visitor identifies their pain point in the Problem section
const stories_103 = `
id: US-103
title: Visitor identifies their pain point in the Problem section
acceptance_criteria:
  - id: AC-103-1
    title: Problem section lists recognizable pain points
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=problem-section]'
    when: []
`;
loadAndRun(stories_103);

// US-104: Visitor understands the four-skill workflow
const stories_104 = `
id: US-104
title: Visitor understands the four-skill workflow
acceptance_criteria:
  - id: AC-104-1
    title: How It Works section shows all four skills
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=how-it-works-section]'
      - shouldContain:
          selector: '[data-test=how-it-works-section]'
          text: rs-init
      - shouldContain:
          selector: '[data-test=how-it-works-section]'
          text: rs-spec
      - shouldContain:
          selector: '[data-test=how-it-works-section]'
          text: rs-impl
      - shouldContain:
          selector: '[data-test=how-it-works-section]'
          text: rs-validate
    when: []
`;
loadAndRun(stories_104);

// US-105: Visitor can navigate to GitHub repo from the site
const stories_105 = `
id: US-105
title: Visitor can navigate to GitHub repo from the site
acceptance_criteria:
  - id: AC-105-1
    title: CTA section contains GitHub link
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=cta-section]'
      - shouldExist:
          selector: '[data-test=cta-github-link]'
    when: []
`;
loadAndRun(stories_105);

// US-301: Visitor explores the five-level RootSpec hierarchy
const stories_301 = `
id: US-301
title: Visitor explores the five-level RootSpec hierarchy
acceptance_criteria:
  - id: AC-301-1
    title: Hierarchy Explorer renders all five levels
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=hierarchy-explorer]'
      - shouldExist:
          selector: '[data-test=hierarchy-level-1]'
      - shouldExist:
          selector: '[data-test=hierarchy-level-2]'
      - shouldExist:
          selector: '[data-test=hierarchy-level-3]'
      - shouldExist:
          selector: '[data-test=hierarchy-level-4]'
      - shouldExist:
          selector: '[data-test=hierarchy-level-5]'
    when: []
  - id: AC-301-2
    title: Clicking a level expands its detail content
    given:
      - visit: /
    when:
      - click:
          selector: '[data-test=hierarchy-level-1]'
    then:
      - shouldExist:
          selector: '[data-test=hierarchy-level-1-content]'
  - id: AC-301-3
    title: Clicking an expanded level collapses it
    given:
      - visit: /
      - click:
          selector: '[data-test=hierarchy-level-1]'
    when:
      - click:
          selector: '[data-test=hierarchy-level-1]'
    then:
      - shouldExist:
          selector: '[data-test=hierarchy-level-1][aria-expanded=false]'
`;
loadAndRun(stories_301);

// US-302: Visitor walks through Spec Wizard and generates a skeleton spec
const stories_302 = `
id: US-302
title: Visitor walks through Spec Wizard and generates a skeleton spec
acceptance_criteria:
  - id: AC-302-1
    title: Spec Wizard renders with first step visible
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=spec-wizard]'
      - shouldExist:
          selector: '[data-test=wizard-step-1]'
    when: []
  - id: AC-302-2
    title: Visitor can complete all wizard steps and see skeleton output
    given:
      - visit: /
    when:
      - fill:
          selector: '[data-test=wizard-product-input]'
          value: A tool for tracking reading habits
      - click:
          selector: '[data-test=wizard-next]'
      - click:
          selector: '[data-test=wizard-next]'
      - click:
          selector: '[data-test=wizard-next]'
    then:
      - shouldExist:
          selector: '[data-test=wizard-output]'
  - id: AC-302-3
    title: Back button is available on all steps after step 1
    given:
      - visit: /
      - click:
          selector: '[data-test=wizard-next]'
    then:
      - shouldExist:
          selector: '[data-test=wizard-back]'
    when: []
`;
loadAndRun(stories_302);

// US-303: Visitor compares spec approach with and without RootSpec
const stories_303 = `
id: US-303
title: Visitor compares spec approach with and without RootSpec
acceptance_criteria:
  - id: AC-303-1
    title: Comparison section renders with both panels
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=comparison-section]'
      - shouldExist:
          selector: '[data-test=comparison-without]'
      - shouldExist:
          selector: '[data-test=comparison-with]'
    when: []
`;
loadAndRun(stories_303);

// US-304: Site renders correctly on mobile viewport
const stories_304 = `
id: US-304
title: Site renders correctly on mobile viewport
acceptance_criteria:
  - id: AC-304-1
    title: Key sections are readable on mobile viewport
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=hero-headline]'
      - shouldExist:
          selector: '[data-test=meta-banner]'
      - shouldExist:
          selector: '[data-test=problem-section]'
    when: []
`;
loadAndRun(stories_304);

// US-401: All interactive elements are keyboard accessible
const stories_401 = `
id: US-401
title: All interactive elements are keyboard accessible
acceptance_criteria:
  - id: AC-401-1
    title: Theme toggle is keyboard accessible
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=theme-toggle][tabindex], [data-test=theme-toggle]:not([tabindex="-1"])'
    when: []
  - id: AC-401-2
    title: Hierarchy Explorer levels are keyboard accessible
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=hierarchy-level-1][tabindex], button[data-test=hierarchy-level-1]'
    when: []
`;
loadAndRun(stories_401);

// US-201: Visitor can toggle between dark and light themes
const stories_201 = `
id: US-201
title: Visitor can toggle between dark and light themes
acceptance_criteria:
  - id: AC-201-1
    title: Theme toggle button is visible in header
    given:
      - visit: /
    then:
      - shouldExist:
          selector: '[data-test=theme-toggle]'
    when: []
  - id: AC-201-2
    title: Clicking theme toggle changes the theme
    given:
      - visit: /
    when:
      - click:
          selector: '[data-test=theme-toggle]'
    then:
      - shouldExist:
          selector: html.dark, html.light
`;
loadAndRun(stories_201);

// US-202: Theme preference persists across page reloads
const stories_202 = `
id: US-202
title: Theme preference persists across page reloads
acceptance_criteria:
  - id: AC-202-1
    title: Dark theme persists after page reload
    given:
      - visit: /
      - click:
          selector: '[data-test=theme-toggle]'
    when:
      - visit: /
    then:
      - shouldExist:
          selector: html.dark
`;
loadAndRun(stories_202);
