import { useState } from 'react';

const pillarOptions = [
  { label: 'Simple', description: 'Every feature should be learnable in under 60 seconds' },
  { label: 'Fast', description: 'Core actions complete in under 500ms' },
  { label: 'Personal', description: 'Data stays private, never shared without consent' },
  { label: 'Collaborative', description: 'Built for teams, not just individuals' },
  { label: 'Transparent', description: 'Users always know what the product is doing and why' },
  { label: 'Resilient', description: 'Works offline, fails gracefully, never loses data' },
];

function generateSkeletonSpec(idea: string, pillars: number[], keyInteraction: string): string {
  const selectedPillars = pillars.map(i => pillarOptions[i]?.label ?? '').filter(Boolean);
  return `# RootSpec Skeleton — Generated by /rs-init

## L1: Philosophy

mission: "${idea}"

design_pillars:
${selectedPillars.map(p => `  - ${p}: [Define what this means for your product]`).join('\n')}

## L2: Truths

success_criteria:
  - [Define how you'll know if users achieve their goal]

trade_offs:
  - [What will you NOT build, and why]

## L3: Interactions

flows:
  key_flow:
    trigger: "${keyInteraction}"
    steps:
      - [Step 1]
      - [Step 2]
      - [Step 3]
    feedback: [What does the user see when done?]

## Next Steps

Run \`/rs-spec\` to expand this into a full validated specification.`;
}

export default function SpecWizard() {
  const [step, setStep] = useState(1);
  const [productIdea, setProductIdea] = useState('');
  const [selectedPillars, setSelectedPillars] = useState<number[]>([]);
  const [keyInteraction, setKeyInteraction] = useState('');
  const [output, setOutput] = useState('');

  const handleNext = () => {
    if (step < 3) setStep(step + 1);
  };

  const handlePillarToggle = (idx: number) => {
    setSelectedPillars(prev =>
      prev.includes(idx) ? prev.filter(i => i !== idx) : [...prev, idx]
    );
  };

  const handleSubmit = () => {
    const spec = generateSkeletonSpec(productIdea, selectedPillars, keyInteraction);
    setOutput(spec);
    setStep(4);
  };

  return (
    <section className="py-20 px-4 sm:px-6 lg:px-8 bg-slate-50 dark:bg-slate-800/30">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 dark:text-white mb-4">
            Spec your idea in 3 steps
          </h2>
          <p className="text-lg text-slate-600 dark:text-slate-300">
            Enter a product idea and walk through the core RootSpec questions.
            No AI — pure methodology.
          </p>
        </div>

        <div
          data-test="spec-wizard"
          className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-700 shadow-sm overflow-hidden"
        >
          {/* Progress bar */}
          {step < 4 && (
            <div className="h-1.5 bg-slate-100 dark:bg-slate-800">
              <div
                className="h-full bg-brand-500 transition-all duration-300"
                style={{ width: `${(step / 3) * 100}%` }}
              />
            </div>
          )}

          <div className="p-6 sm:p-8">
            {/* Step 1 */}
            {step === 1 && (
              <div data-test="wizard-step-1">
                <div className="mb-6">
                  <span className="text-xs font-mono text-brand-500 uppercase tracking-wider">Step 1 of 3 · L1 Philosophy</span>
                  <h3 className="text-xl font-bold text-slate-900 dark:text-white mt-1">
                    What is your product's mission?
                  </h3>
                  <p className="text-slate-500 dark:text-slate-400 mt-1 text-sm">
                    One sentence: who does it help and what problem does it solve?
                  </p>
                </div>
                <textarea
                  data-test="wizard-product-idea"
                  value={productIdea}
                  onChange={e => setProductIdea(e.target.value)}
                  placeholder="e.g. A tool for tracking reading habits and building reflection rituals"
                  rows={3}
                  className="w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 resize-none"
                />
                <div className="mt-4 flex justify-end">
                  <button
                    data-test="wizard-next"
                    onClick={handleNext}
                    disabled={!productIdea.trim()}
                    className="px-6 py-2.5 rounded-lg bg-brand-600 hover:bg-brand-700 disabled:opacity-40 disabled:cursor-not-allowed text-white font-medium text-sm transition-colors"
                  >
                    Next: Design pillars →
                  </button>
                </div>
              </div>
            )}

            {/* Step 2 */}
            {step === 2 && (
              <div data-test="wizard-step-2">
                <div className="mb-6">
                  <span className="text-xs font-mono text-brand-500 uppercase tracking-wider">Step 2 of 3 · L1 Philosophy</span>
                  <h3 className="text-xl font-bold text-slate-900 dark:text-white mt-1">
                    What should users feel?
                  </h3>
                  <p className="text-slate-500 dark:text-slate-400 mt-1 text-sm">
                    Pick 2–4 design pillars. These constrain every future decision.
                  </p>
                </div>
                <div className="grid sm:grid-cols-2 gap-3 mb-6">
                  {pillarOptions.map((option, idx) => (
                    <button
                      key={idx}
                      data-test={`wizard-pillar-option-${idx}`}
                      onClick={() => handlePillarToggle(idx)}
                      className={`text-left p-4 rounded-lg border-2 transition-all ${
                        selectedPillars.includes(idx)
                          ? 'border-brand-500 bg-brand-50 dark:bg-brand-900/20'
                          : 'border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600'
                      }`}
                    >
                      <p className={`font-medium text-sm ${selectedPillars.includes(idx) ? 'text-brand-700 dark:text-brand-300' : 'text-slate-900 dark:text-white'}`}>
                        {selectedPillars.includes(idx) ? '✓ ' : ''}{option.label}
                      </p>
                      <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{option.description}</p>
                    </button>
                  ))}
                </div>
                <div className="flex justify-between">
                  <button
                    onClick={() => setStep(1)}
                    className="px-4 py-2 text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"
                  >
                    ← Back
                  </button>
                  <button
                    data-test="wizard-next"
                    onClick={handleNext}
                    disabled={selectedPillars.length === 0}
                    className="px-6 py-2.5 rounded-lg bg-brand-600 hover:bg-brand-700 disabled:opacity-40 disabled:cursor-not-allowed text-white font-medium text-sm transition-colors"
                  >
                    Next: Key interaction →
                  </button>
                </div>
              </div>
            )}

            {/* Step 3 */}
            {step === 3 && (
              <div>
                <div className="mb-6">
                  <span className="text-xs font-mono text-brand-500 uppercase tracking-wider">Step 3 of 3 · L3 Interactions</span>
                  <h3 className="text-xl font-bold text-slate-900 dark:text-white mt-1">
                    Describe one key interaction
                  </h3>
                  <p className="text-slate-500 dark:text-slate-400 mt-1 text-sm">
                    The single most important thing a user will do in your product.
                  </p>
                </div>
                <textarea
                  data-test="wizard-key-interaction"
                  value={keyInteraction}
                  onChange={e => setKeyInteraction(e.target.value)}
                  placeholder="e.g. User logs a book they finished reading"
                  rows={2}
                  className="w-full rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 resize-none mb-4"
                />
                <div className="flex justify-between">
                  <button
                    onClick={() => setStep(2)}
                    className="px-4 py-2 text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"
                  >
                    ← Back
                  </button>
                  <button
                    data-test="wizard-submit"
                    onClick={handleSubmit}
                    disabled={!keyInteraction.trim()}
                    className="px-6 py-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 disabled:opacity-40 disabled:cursor-not-allowed text-white font-medium text-sm transition-colors"
                  >
                    Generate skeleton spec →
                  </button>
                </div>
              </div>
            )}

            {/* Output */}
            {step === 4 && (
              <div>
                <div className="mb-6">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="text-emerald-500 font-bold">✓</span>
                    <span className="text-xs font-mono text-emerald-600 dark:text-emerald-400 uppercase tracking-wider">Skeleton spec generated</span>
                  </div>
                  <h3 className="text-xl font-bold text-slate-900 dark:text-white">
                    Your L1–L3 skeleton
                  </h3>
                  <p className="text-slate-500 dark:text-slate-400 text-sm mt-1">
                    Run <code className="font-mono bg-slate-100 dark:bg-slate-800 px-1 rounded">/rs-spec</code> to expand this into a full validated specification.
                  </p>
                </div>
                <pre
                  data-test="wizard-output"
                  className="text-xs font-mono bg-slate-50 dark:bg-slate-800 rounded-xl p-5 overflow-x-auto text-slate-700 dark:text-slate-300 leading-relaxed border border-slate-200 dark:border-slate-700 whitespace-pre-wrap"
                >
                  {output}
                </pre>
                <div className="mt-4 flex justify-end">
                  <button
                    onClick={() => { setStep(1); setProductIdea(''); setSelectedPillars([]); setKeyInteraction(''); setOutput(''); }}
                    className="px-4 py-2 text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300"
                  >
                    Start over
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
