import { useState } from 'react';

const MISSION_TEMPLATES = [
  'To give {audience} the ability to {capability} without {friction}',
  'To make {domain} accessible to people who {currently excluded}',
  'To replace {painful process} with something that {desired outcome}',
];

const PILLAR_SUGGESTIONS = [
  'Effortless Clarity',
  'Calm Control',
  'Earned Confidence',
  'Delightful Discovery',
  'Focused Flow',
  'Trusted Precision',
];

type Step = 1 | 2 | 3 | 'output';

function generateSpec(productIdea: string, mission: string, pillars: string[], interaction: string): string {
  return `# Skeleton RootSpec — Generated from Your Input

## L1: Foundational Philosophy

**Mission**
${mission || `To give users a better way to ${productIdea.toLowerCase()}`}

**Design Pillars**
${pillars.map((p, i) => `${i + 1}. ${p}`).join('\n')}

---

## L2: Stable Truths

${pillars.slice(0, 2).map(p => `**Truth: ${p} is non-negotiable**
The design of every feature must reinforce ${p.toLowerCase()}.
When trade-offs arise, ${p.toLowerCase()} takes precedence over convenience.
`).join('\n')}

---

## L3: Core Interaction

**Flow: ${interaction.split(' ').slice(0, 5).join(' ')}...**
${interaction}

This interaction is the product's primary value delivery moment.
Every other interaction supports or enables this one.

---

*Generated by RootSpec Spec Wizard — this is a starting point, not a finished spec.*
*Run \`/rs-spec\` to deepen and validate your specification.*`;
}

export default function SpecWizard() {
  const [step, setStep] = useState<Step>(1);
  const [productIdea, setProductIdea] = useState('');
  const [mission, setMission] = useState('');
  const [selectedPillars, setSelectedPillars] = useState<string[]>([]);
  const [customPillar, setCustomPillar] = useState('');
  const [interaction, setInteraction] = useState('');
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const handleNext1 = () => {
    if (productIdea.trim().length >= 5) setStep(2);
  };

  const togglePillar = (p: string) => {
    setSelectedPillars(prev =>
      prev.includes(p)
        ? prev.filter(x => x !== p)
        : prev.length < 5 ? [...prev, p] : prev
    );
  };

  const addCustomPillar = () => {
    if (customPillar.trim().length >= 3 && selectedPillars.length < 5) {
      setSelectedPillars(prev => [...prev, customPillar.trim()]);
      setCustomPillar('');
    }
  };

  const handleGenerate = () => {
    const spec = generateSpec(productIdea, mission, selectedPillars, interaction);
    setOutput(spec);
    setStep('output');
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(output).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleStartOver = () => {
    setStep(1);
    setProductIdea('');
    setMission('');
    setSelectedPillars([]);
    setCustomPillar('');
    setInteraction('');
    setOutput('');
    setCopied(false);
  };

  const inputStyle: React.CSSProperties = {
    width: '100%',
    padding: '8px 12px',
    fontFamily: 'Inter, sans-serif',
    fontSize: '14px',
    border: '1px solid var(--color-border)',
    borderRadius: '4px',
    backgroundColor: 'var(--color-bg)',
    color: 'var(--color-text)',
    outline: 'none',
    boxSizing: 'border-box',
  };

  const btnPrimary: React.CSSProperties = {
    padding: '8px 20px',
    fontFamily: 'Inter, sans-serif',
    fontSize: '13px',
    fontWeight: 500,
    borderRadius: '4px',
    border: 'none',
    cursor: 'pointer',
    transition: 'opacity 150ms ease-out',
  };

  const btnSecondary: React.CSSProperties = {
    ...btnPrimary,
    backgroundColor: 'transparent',
    border: '1px solid var(--color-border)',
    color: 'var(--color-text-muted)',
  };

  return (
    <div data-test="spec-wizard" style={{ width: '100%' }}>
      {/* Step indicator */}
      <div style={{ marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '8px' }}>
        {([1, 2, 3] as const).map(s => (
          <div
            key={s}
            style={{
              width: '24px',
              height: '24px',
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontFamily: 'Inter, sans-serif',
              fontSize: '12px',
              fontWeight: '500',
              backgroundColor: step === s || (step === 'output') ? 'var(--color-accent)' : (
                (s === 1 && (step === 2 || step === 3 || step === 'output')) ||
                (s === 2 && (step === 3 || step === 'output')) ||
                (s === 3 && step === 'output')
              ) ? 'var(--color-surface)' : 'var(--color-surface)',
              color: step === s ? 'white' : 'var(--color-text-muted)',
              border: step === s ? 'none' : '1px solid var(--color-border)',
            }}
          >
            {s}
          </div>
        ))}
        <span style={{ fontFamily: 'Inter, sans-serif', fontSize: '12px', color: 'var(--color-text-muted)' }}>
          {step === 'output' ? 'Output ready' : `Step ${step} of 3`}
        </span>
      </div>

      {/* Step 1 */}
      {step === 1 && (
        <div data-test="wizard-step-1">
          <h3 style={{ fontFamily: 'Inter, sans-serif', fontSize: '16px', fontWeight: '500', marginBottom: '6px', color: 'var(--color-text)' }}>
            What's your product idea?
          </h3>
          <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '13px', color: 'var(--color-text-muted)', marginBottom: '12px' }}>
            One sentence describing what you're building.
          </p>
          <input
            data-test="product-idea-input"
            type="text"
            value={productIdea}
            onChange={(e) => setProductIdea(e.target.value)}
            placeholder="e.g. A tool for tracking personal goals and building habits"
            style={inputStyle}
          />

          <div style={{ marginTop: '16px' }}>
            <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '13px', color: 'var(--color-text-muted)', marginBottom: '8px' }}>
              Mission (optional — pick a template or write your own):
            </p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', marginBottom: '8px' }}>
              {MISSION_TEMPLATES.map(t => (
                <button
                  key={t}
                  onClick={() => setMission(mission === t ? '' : t)}
                  style={{
                    padding: '8px 12px',
                    textAlign: 'left',
                    fontFamily: 'Inter, sans-serif',
                    fontSize: '13px',
                    border: '1px solid var(--color-border)',
                    borderRadius: '4px',
                    cursor: 'pointer',
                    backgroundColor: mission === t ? 'var(--color-surface)' : 'var(--color-bg)',
                    color: 'var(--color-text-muted)',
                    transition: 'all 150ms ease-out',
                  }}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          <div style={{ marginTop: '20px', display: 'flex', justifyContent: 'flex-end' }}>
            <button
              data-test="wizard-next"
              onClick={handleNext1}
              disabled={productIdea.trim().length < 5}
              style={{
                ...btnPrimary,
                backgroundColor: 'var(--color-accent)',
                color: 'white',
                opacity: productIdea.trim().length < 5 ? 0.4 : 1,
                cursor: productIdea.trim().length < 5 ? 'not-allowed' : 'pointer',
              }}
            >
              Next →
            </button>
          </div>
        </div>
      )}

      {/* Step 2 */}
      {step === 2 && (
        <div data-test="wizard-step-2">
          <h3 style={{ fontFamily: 'Inter, sans-serif', fontSize: '16px', fontWeight: '500', marginBottom: '6px', color: 'var(--color-text)' }}>
            What should users feel?
          </h3>
          <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '13px', color: 'var(--color-text-muted)', marginBottom: '12px' }}>
            Pick 1–5 design pillars that capture the emotional quality of your product.
          </p>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginBottom: '12px' }}>
            {PILLAR_SUGGESTIONS.map(p => (
              <button
                key={p}
                onClick={() => togglePillar(p)}
                style={{
                  padding: '6px 12px',
                  fontFamily: 'Inter, sans-serif',
                  fontSize: '13px',
                  border: '1px solid var(--color-border)',
                  borderRadius: '20px',
                  cursor: 'pointer',
                  backgroundColor: selectedPillars.includes(p) ? 'var(--color-accent)' : 'var(--color-bg)',
                  color: selectedPillars.includes(p) ? 'white' : 'var(--color-text-muted)',
                  transition: 'all 150ms ease-out',
                }}
              >
                {p}
              </button>
            ))}
          </div>
          <div style={{ display: 'flex', gap: '8px', marginBottom: '8px' }}>
            <input
              type="text"
              value={customPillar}
              onChange={(e) => setCustomPillar(e.target.value)}
              onKeyDown={(e) => { if (e.key === 'Enter') addCustomPillar(); }}
              placeholder="Add custom pillar..."
              style={{ ...inputStyle, flex: 1 }}
            />
            <button onClick={addCustomPillar} style={{ ...btnSecondary, padding: '8px 12px' }}>Add</button>
          </div>
          {selectedPillars.length > 0 && (
            <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '12px', color: 'var(--color-text-muted)' }}>
              Selected: {selectedPillars.join(', ')}
            </p>
          )}
          <div style={{ marginTop: '20px', display: 'flex', justifyContent: 'space-between' }}>
            <button onClick={() => setStep(1)} style={btnSecondary}>← Back</button>
            <button
              data-test="wizard-next"
              onClick={() => setStep(3)}
              disabled={selectedPillars.length < 1}
              style={{
                ...btnPrimary,
                backgroundColor: 'var(--color-accent)',
                color: 'white',
                opacity: selectedPillars.length < 1 ? 0.4 : 1,
                cursor: selectedPillars.length < 1 ? 'not-allowed' : 'pointer',
              }}
            >
              Next →
            </button>
          </div>
        </div>
      )}

      {/* Step 3 */}
      {step === 3 && (
        <div data-test="wizard-step-3">
          <h3 style={{ fontFamily: 'Inter, sans-serif', fontSize: '16px', fontWeight: '500', marginBottom: '6px', color: 'var(--color-text)' }}>
            Describe one key interaction
          </h3>
          <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '13px', color: 'var(--color-text-muted)', marginBottom: '12px' }}>
            The most important thing a user does in your product. One sentence or a short paragraph.
          </p>
          <textarea
            value={interaction}
            onChange={(e) => setInteraction(e.target.value)}
            placeholder="e.g. The user opens the app in the morning, sees their top 3 goals for the day, marks progress on each, and closes with a sense of what they accomplished."
            rows={4}
            style={{ ...inputStyle, resize: 'vertical' }}
          />
          <div style={{ marginTop: '20px', display: 'flex', justifyContent: 'space-between' }}>
            <button onClick={() => setStep(2)} style={btnSecondary}>← Back</button>
            <button
              onClick={handleGenerate}
              disabled={interaction.trim().length < 10}
              style={{
                ...btnPrimary,
                backgroundColor: 'var(--color-accent)',
                color: 'white',
                opacity: interaction.trim().length < 10 ? 0.4 : 1,
                cursor: interaction.trim().length < 10 ? 'not-allowed' : 'pointer',
              }}
            >
              Generate Spec →
            </button>
          </div>
        </div>
      )}

      {/* Output */}
      {step === 'output' && (
        <div data-test="wizard-output">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
            <h3 style={{ fontFamily: 'Inter, sans-serif', fontSize: '16px', fontWeight: '500', color: 'var(--color-text)', margin: 0 }}>
              Your skeleton spec
            </h3>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button onClick={handleCopy} style={btnSecondary}>
                {copied ? 'Copied!' : 'Copy'}
              </button>
              <button onClick={handleStartOver} style={btnSecondary}>Start over</button>
            </div>
          </div>
          <pre
            style={{
              fontFamily: 'JetBrains Mono, monospace',
              fontSize: '12px',
              lineHeight: '1.7',
              color: 'var(--color-text)',
              backgroundColor: 'var(--color-code-bg)',
              padding: '16px',
              borderRadius: '6px',
              border: '1px solid var(--color-border)',
              overflow: 'auto',
              whiteSpace: 'pre-wrap',
              maxHeight: '500px',
            }}
          >
            {output}
          </pre>
          <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '12px', color: 'var(--color-text-muted)', marginTop: '12px' }}>
            Run <code style={{ fontFamily: 'JetBrains Mono, monospace', backgroundColor: 'var(--color-code-bg)', padding: '1px 4px', borderRadius: '3px' }}>/rs-spec</code> to turn this skeleton into a fully validated specification.
          </p>
        </div>
      )}
    </div>
  );
}
